### ISSUE TITLE
Initial zoom value is too big for the small images

### ISSUE THREAD

**Issue by yur-puz** [avironman/OMRON---IFZ-Viewer#2]
Somehow it starts with 152% zoom for image 640x480 - why? 
It makes sense to shrink image if it not fits in the screen resolution, not to enlarge it (if it fits). 

![2024-10-31_16-51-45](https://github.com/user-attachments/assets/f209ac18-f980-4f7e-8efe-c8753d584610)

**Comment by avironman** [comment]
Not a bug
![image](https://github.com/user-attachments/assets/c16150de-b2e9-4cbc-be7b-ba8d38d8823b)
